# Generated by Django 5.1.5 on 2025-03-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cross Ref')),
                ('product_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='PID Desc')),
                ('blu', models.CharField(max_length=100, verbose_name='Adjusted RLJ Item')),
                ('mkst', models.CharField(max_length=50, verbose_name='Mkst')),
                ('currect_fc_index', models.CharField(blank=True, max_length=50, null=True, verbose_name='FC Index')),
                ('safe_non_safe', models.CharField(max_length=20, verbose_name='Safe/Non-Safe')),
                ('item_code', models.CharField(max_length=20, verbose_name='Item Code')),
                ('current_door_count', models.IntegerField(blank=True, null=True, verbose_name='Door Count')),
                ('last_store_count', models.IntegerField(blank=True, null=True, verbose_name='Old Door Count')),
                ('door_count_updated', models.DateField(blank=True, null=True, verbose_name='Door Count Updated')),
                ('store_model', models.IntegerField(blank=True, null=True, verbose_name='Model')),
                ('com_model', models.IntegerField(blank=True, null=True, verbose_name='Com Model')),
                ('holiday_build_fc', models.IntegerField(blank=True, null=True, verbose_name='HolidayBuildFC')),
                ('macys_onhand', models.IntegerField(blank=True, null=True, verbose_name='MCYOH Units')),
                ('oo', models.IntegerField(blank=True, null=True, verbose_name='OO Units')),
                ('in_transit', models.IntegerField(blank=True, null=True, verbose_name='nav OO')),
                ('month_to_date_shipment', models.IntegerField(blank=True, null=True, verbose_name='MTD SHIPMENTS')),
                ('lastweek_shipment', models.IntegerField(blank=True, null=True, verbose_name='LW Shipments')),
                ('planned_weeks_of_stock', models.IntegerField(blank=True, null=True, verbose_name='Wks of Stock OH')),
                ('weeks_of_projection', models.IntegerField(blank=True, null=True, verbose_name='Wks of on Proj')),
                ('last_4weeks_shipment', models.IntegerField(blank=True, null=True, verbose_name='Last 3Wks Ships')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('min_order', models.IntegerField(blank=True, null=True, verbose_name='Min Order')),
                ('rl_total', models.IntegerField(blank=True, null=True, verbose_name='Proj')),
                ('net_projection', models.IntegerField(blank=True, null=True, verbose_name='Net Proj')),
                ('unalloc_order', models.IntegerField(blank=True, null=True, verbose_name='Unalloc Orders')),
                ('ma_bin', models.IntegerField(blank=True, null=True, verbose_name='RLJ OH')),
                ('fldc', models.IntegerField(blank=True, null=True, verbose_name='FLDC')),
                ('wip_quantity', models.IntegerField(blank=True, null=True, verbose_name='WIP')),
                ('md_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='MD Status MZ1')),
                ('replanishment_flag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Repl Flag')),
                ('mcom_replanishment', models.CharField(blank=True, max_length=20, null=True, verbose_name='MCOM RPL')),
                ('pool_stock', models.IntegerField(blank=True, null=True, verbose_name='Pool Stock')),
                ('first_reciept_date', models.DateField(blank=True, null=True, verbose_name='1st Rec Date')),
                ('last_reciept_date', models.DateField(blank=True, null=True, verbose_name='Last Rec Date')),
                ('item_age', models.IntegerField(blank=True, null=True, verbose_name='Item Age')),
                ('first_live_date', models.DateField(blank=True, null=True, verbose_name='1st Live')),
                ('this_year_last_cost', models.FloatField(blank=True, null=True, verbose_name='TY Last Cost')),
                ('macys_owned_retail', models.FloatField(blank=True, null=True, verbose_name='Own Retail')),
                ('awr_first_ticket_retail', models.FloatField(blank=True, null=True, verbose_name='AWR 1st Tkt Ret')),
                ('metal_lock', models.FloatField(blank=True, null=True, verbose_name='Metal Lock')),
                ('mfg_policy', models.CharField(blank=True, max_length=50, null=True, verbose_name='MFG Policy')),
                ('kpi_data_updated', models.CharField(blank=True, max_length=50, null=True, verbose_name='KPI Data Updated')),
                ('kpi_door_count', models.IntegerField(blank=True, null=True, verbose_name='KPI Door count')),
                ('out_of_stock_location', models.IntegerField(blank=True, null=True, verbose_name='OOS Locs')),
                ('suspended_location_count', models.IntegerField(blank=True, null=True, verbose_name='Suspended Loc Count')),
                ('live_site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Live Site')),
                ('masterstyle_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Masterstyle Desc')),
                ('masterstyle_id', models.IntegerField(blank=True, null=True, verbose_name='MstrSt ID')),
                ('department_id', models.IntegerField(blank=True, null=True, verbose_name='Dpt ID')),
                ('department_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dpt Desc')),
                ('subclass_id', models.IntegerField(blank=True, null=True, verbose_name='SC ID')),
                ('subclass_decription', models.CharField(blank=True, max_length=100, null=True, verbose_name='SC Desc')),
                ('webid_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prod Desc')),
                ('v2c', models.CharField(blank=True, max_length=50, null=True, verbose_name='V2C')),
                ('marketing_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mktg ID')),
                ('std_store_return', models.FloatField(blank=True, null=True, verbose_name='STD Store Rtn %')),
                ('last_project_review_date', models.DateField(blank=True, null=True, verbose_name='Last Proj Review Date')),
                ('macy_spring_projection_note', models.TextField(blank=True, null=True, verbose_name="Macy's Spring Proj Notes")),
                ('planner_response', models.TextField(blank=True, null=True, verbose_name='Planner Response')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(choices=[('MacysProjectionReciepts', 'Macys Projection Receipts'), ('PlannedEOH', 'Planned EOH'), ('PlannedShipment', 'Planned Shipment'), ('PlannedForecast', 'Planned Forecast'), ('RecommendedForecast', 'Recommended Forecast'), ('ForecastByTrend', 'Forecast By Trend'), ('IndexPercentage', 'Index Percentage'), ('GrossProjection', 'Gross Projection'), ('TY_Unit_Sales', 'This Year Unit Sales'), ('LY_Unit_Sales', 'Last Year Unit Sales'), ('LY_OH_Units', 'Last Year On-Hand Units'), ('TY_OH_Units', 'This Year On-Hand Units'), ('TY_Receipts', 'This Year Receipts'), ('LY_Receipts', 'Last Year Receipts'), ('TY_MCOM_Unit_Sales', 'This Year MCOM Unit Sales'), ('LY_MCOM_Unit_Sales', 'Last Year MCOM Unit Sales'), ('TY_OH_MCOM_Units', 'This Year MCOM On-Hand Units'), ('LY_MCOM_OH_Units', 'Last Year MCOM On-Hand Units'), ('PTD_TY_Sales', 'PTD This Year Sales'), ('LY_PTD_Sales', 'Last Year PTD Sales'), ('MCOM_PTD_TY_Sales', 'MCOM PTD This Year Sales'), ('MCOM_PTD_LY_Sales', 'MCOM PTD Last Year Sales'), ('OO_Total_Units', 'OO Total Units'), ('OO_MCOM_Total_Units', 'OO MCOM Total Units')], max_length=50, verbose_name='Variable')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('value', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.productdetail', verbose_name='Product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'variable_name'], name='forecast_mo_product_044781_idx'), models.Index(fields=['year', 'month'], name='forecast_mo_year_769fde_idx')],
                'unique_together': {('product', 'variable_name', 'year', 'month')},
            },
        ),
    ]
