# Generated by Django 5.1.5 on 2025-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='item_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='safe_non_safe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Safe/Non-Safe'),
        ),
    ]
