# Generated by Django 5.1.5 on 2025-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_productdetail_blu_alter_productdetail_mkst'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlyforecast',
            name='forecast_mo_year_769fde_idx',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyforecast',
            unique_together={('product', 'variable_name', 'year')},
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='apr',
            field=models.IntegerField(blank=True, null=True, verbose_name='April'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='aug',
            field=models.IntegerField(blank=True, null=True, verbose_name='August'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='dec',
            field=models.IntegerField(blank=True, null=True, verbose_name='December'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='feb',
            field=models.IntegerField(blank=True, null=True, verbose_name='February'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='jan',
            field=models.IntegerField(blank=True, null=True, verbose_name='January'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='jul',
            field=models.IntegerField(blank=True, null=True, verbose_name='July'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='jun',
            field=models.IntegerField(blank=True, null=True, verbose_name='June'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='mar',
            field=models.IntegerField(blank=True, null=True, verbose_name='March'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='may',
            field=models.IntegerField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='nov',
            field=models.IntegerField(blank=True, null=True, verbose_name='November'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='oct',
            field=models.IntegerField(blank=True, null=True, verbose_name='October'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='sep',
            field=models.IntegerField(blank=True, null=True, verbose_name='September'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['year'], name='forecast_mo_year_f6647c_idx'),
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='value',
        ),
    ]
