# Generated by Django 5.1.5 on 2025-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_remove_monthlyforecast_forecast_mo_year_769fde_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='mcom_replanishment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MCOM RPL'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='replanishment_flag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Repl Flag'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='safe_non_safe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Safe/Non-Safe'),
        ),
    ]
