# Generated by Django 5.1.5 on 2025-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_comforecast_omniforecast_storeforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeforecast',
            name='birthstone_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
