# Generated by Django 5.1.5 on 2025-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_alter_storeforecast_birthstone_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omniforecast',
            name='birthstone_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
