# Generated by Django 5.1.5 on 2025-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_alter_omniforecast_birthstone_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omniforecast',
            old_name='forecasting_method',
            new_name='forecasting_method_com',
        ),
        migrations.RemoveField(
            model_name='omniforecast',
            name='forecast_month_required_quantity',
        ),
        migrations.RemoveField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity',
        ),
        migrations.RemoveField(
            model_name='omniforecast',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='omniforecast',
            name='trend_index_difference',
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Added_only_to_balance_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Added_qty_using_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Below_min_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Fathers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Macys_SOQ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Mens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Min_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Mothers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Need_to_review_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Over_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Qty_given_to_macys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='RLJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Valentine_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='Womens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Added_only_to_balance_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Added_qty_using_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Below_min_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Fathers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Macys_SOQ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Mens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Min_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Mothers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Need_to_review_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Over_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Qty_given_to_macys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='RLJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Valentine_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='Womens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecast_month_required_quantity_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecast_month_required_quantity_store',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecast_month_required_quantity_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecasting_method_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity_store',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='store_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='trend_index_difference_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='trend_index_difference_store',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Added_only_to_balance_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Added_qty_using_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Below_min_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Fathers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Macys_SOQ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Mens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Min_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Mothers_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Need_to_review_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Over_macys_SOQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Qty_given_to_macys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='RLJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Valentine_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='Womens_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
